// <auto-generated />
using System;
using EsteticaRepositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EsteticaRepositorio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429232904_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EsteticaDominio.Consulta.Consultas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Fim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("Inicio")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TipoConsultaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Valor")
                        .HasPrecision(16, 2)
                        .HasColumnType("NUMERIC(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TipoConsultaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("EsteticaDominio.Consulta.HorarioConsultas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("Fim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("Inicio")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("HorarioConsultas");
                });

            modelBuilder.Entity("EsteticaDominio.Consulta.HorariosIndisponiveis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Fim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("Inicio")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("HorariosIndisponiveis");
                });

            modelBuilder.Entity("EsteticaDominio.Consulta.TipoConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("bytea");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("UriImagem")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorAtual")
                        .HasPrecision(16, 2)
                        .HasColumnType("NUMERIC(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TipoConsulta");
                });

            modelBuilder.Entity("EsteticaDominio.Consulta.TipoConsultaHorarios", b =>
                {
                    b.Property<int>("TipoConsultaId")
                        .HasColumnType("integer");

                    b.Property<int>("HorarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Reservado")
                        .HasColumnType("boolean");

                    b.HasKey("TipoConsultaId", "HorarioId");

                    b.HasIndex("HorarioId");

                    b.ToTable("TipoConsultaHorarios");
                });

            modelBuilder.Entity("EsteticaDominio.Produtos.Produtos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("EstimativaEntrega")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("bytea");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("TipoProdutosId")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadeMedida")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("UriImagem")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorDeCusto")
                        .HasPrecision(16, 2)
                        .HasColumnType("NUMERIC(18,2)");

                    b.Property<decimal>("ValorDeVenda")
                        .HasPrecision(16, 2)
                        .HasColumnType("NUMERIC(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TipoProdutosId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("EsteticaDominio.Produtos.TipoProdutos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoProdutos");
                });

            modelBuilder.Entity("EsteticaDominio.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<char>("Genero")
                        .HasColumnType("character(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("NotificacaoToken")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimeiroNome")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UltimoNome")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("EsteticaDominio.Consulta.Consultas", b =>
                {
                    b.HasOne("EsteticaDominio.Consulta.TipoConsulta", "TipoConsulta")
                        .WithMany("Consultas")
                        .HasForeignKey("TipoConsultaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EsteticaDominio.Usuarios", "Usuario")
                        .WithMany("Consultas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoConsulta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EsteticaDominio.Consulta.TipoConsultaHorarios", b =>
                {
                    b.HasOne("EsteticaDominio.Consulta.HorarioConsultas", "Horario")
                        .WithMany("TipoConsultaHorarios")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EsteticaDominio.Consulta.TipoConsulta", "TipoConsulta")
                        .WithMany("TipoConsultaHorarios")
                        .HasForeignKey("TipoConsultaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Horario");

                    b.Navigation("TipoConsulta");
                });

            modelBuilder.Entity("EsteticaDominio.Produtos.Produtos", b =>
                {
                    b.HasOne("EsteticaDominio.Produtos.TipoProdutos", "TipoProdutos")
                        .WithMany("Produtos")
                        .HasForeignKey("TipoProdutosId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TipoProdutos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("EsteticaDominio.Usuarios", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsteticaDominio.Consulta.HorarioConsultas", b =>
                {
                    b.Navigation("TipoConsultaHorarios");
                });

            modelBuilder.Entity("EsteticaDominio.Consulta.TipoConsulta", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("TipoConsultaHorarios");
                });

            modelBuilder.Entity("EsteticaDominio.Produtos.TipoProdutos", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("EsteticaDominio.Usuarios", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
