# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build (.NET 9)
    runs-on: windows-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Restaurar dependencias
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Lint (Format check)
        run: dotnet format --verify-no-changes --no-restore
